spring:
  application:
    name: user4a
    version: 1.0.0
  banner:
    location: classpath:/banner-text.txt
  datasource:
    url: jdbc:postgresql://${THREAD_DB_HOST}:${THREAD_DB_PORT}/${THREAD_DB_NAME}
    username: ${THREAD_DB_USERNAME}
    password: ${THREAD_DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
